version: '3'
services:
  nodeapp:
     build: .
     ports:
      - "3000:3000"
     volumes:
       - ./:/app
       - /app/node_modules
     environment:
       - PORT=3000
     depends_on:
       - mongo  

  mongo:
     image: mongo:5.0
     environment:
       - MONGO_INITDB_ROOT_USERNAME=raj
       - MONGO_INITDB_ROOT_PASSWORD=1234
     volumes:
       - mongo-dbname:/data/db

volumes:
  mongo-dbname: